name: bazzite-gamedev
description: Bazzite DX Custom Image
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: stable

modules:
  - type: rpm-ostree
    repos: []
    install:
      - btop
      - tree
      - blender

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        install:
          - dev.vencord.Vesktop
          - com.spotify.Client
          - dev.zed.Zed
          - com.google.Chrome
